name: "Feature request"
description: "Suggest an idea or enhancement for this project"
labels: "Feature+Request"

body:
- type: markdown
  attributes:
    value: |
      ## Proposing a Feature? 💡

      - **First**, search if a similar request has already been proposed. Let's avoid duplicates.
      - **Describe** the problem and solution in detail. It helps us understand your perspective and needs.

- type: input
  attributes:
    label: "BMS Version 🔄"
    description: "Specify the version of the BMS you are using. It can help contextualize the feature request."
  validations:
    required: true
  
- type: dropdown
  attributes:
    label: "Connection Method 🌐"
    description: "How is the BMS connected to your system? This can give insights into the applicability of the feature."
    options:
      - "USB-RS485"
      - "ESP8266"
      - "ESP32"
      - "Other (please specify)"
  validations:
    required: true

- type: textarea
  attributes:
    label: "Problem Description 🤔"
    description: "Is your feature request related to a problem? Please provide a clear description of what the problem is."
    placeholder: "I'm always frustrated when [...]"
  validations:
    required: true

- type: textarea
  attributes:
    label: "Proposed Solution 🛠️"
    description: "Describe the solution you'd like to see implemented. Be as detailed as possible."
  validations:
    required: true

- type: textarea
  attributes:
    label: "Alternatives Considered 🔄"
    description: "Have you thought of other ways to address this problem or similar features? Share them here."
  validations:
    required: false

- type: textarea
  attributes:
    label: "Additional context 📄"
    description: "Provide any other relevant details, context, or screenshots about the feature request. It helps us get a fuller picture."
  validations:
    required: false
